# fly.toml app configuration file generated for quotesapi on 2025-04-26T14:43:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quotesapi'
primary_region = 'ams'

[env]
  jwt_jwksUri = 'https://dev-wzfkg4o26oz6ndmt.us.auth0.com/.well-known/jwks.json'
  jwt_audience = 'quotes.programmersdiary.com'
  jwt_issuer = 'https://dev-wzfkg4o26oz6ndmt.us.auth0.com/'
  jwt_customClaimsNamespace = 'https://quotes.programmersdiary.com/'

  db_name = 'Quotes'
  db_quotesCollectionName = 'Quotes'
  db_usersCollectionName = 'Users'

  quotes_randomFetchSize = 5

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  